#!/bin/bash
#simple calculator

clear

echo -e " \e[1;31m                   [[ My Calculator!, Version-1.0.0 ]] \e[0m "

while [ 1  ]
	
do
echo -e "---------------------------------------------------------------------------------------"
echo -e "\e[1;34m                   TO Exit Type 'q' Or Press CTRL+C and enter\e[0m"
echo -e "\e[1;36m ________________________________________________________\e[0m"
echo -e "\e[1;36m |Enter a operation: root | + | - | / | x | ^ | rem | % |\e[0m"
echo -e "\e[1;34m --------------------------------------------------------\e[0m"
echo -e " \e[1;3;5;31m >>> \e[0m"
read -p  "Option:" op

if [ $op = 'q' ]
then
	break
elif [ $op = 'root' ]
then
	read -p "Enter a number:" x
	echo -e " \e[1;33m  sqrt($x)=$(echo "sqrt(9)" | bc) \e[0m"
else
read -p " Enter first number: " v1

read -p " Enter second number: " v2



if   [ $op = '+' ]
then
	echo -e " \e[1;33m #$v1+$v2=$(echo "scale=5;$v1 + $v2 " | bc) \e[0m"
elif [ $op = '-' ]
then
	echo -e "\e[1;33m #$v1-$v2=$(echo "scale=5;$v1 - $v2" | bc) \e[0m"
elif [ $op = 'x' ]
then
	echo -e "\e[1;33m #$v1 X $v2=$(echo "scale=5;$v1 * $v2" | bc) \e[0m"
elif [ $op = '/' ] 
then
	echo -e "\e[1;33m #$v1/$v2=$(echo " scale=5;$v1 / $v2 " | bc) \e[0m"
elif [ $op = '^' ]
then
	echo -e "\e[1;33m #$v1^$v2=$(echo "scale=5;$v1 ^ $v2  " | bc) \e[0m"
elif [ $op = 'rem' ]
then
	echo -e "\e[1;33m #remainder:$(echo "scale=5;$v1 % $v2 " | bc)\e[0m"
elif [ $op = '%' ] 
then
	a=$(echo "scale=2;( $v1 * 100 ) / $v2 " | bc)
	echo -e "\e[1;33m #$v1 is $a% of $v2 \e[0m"
else
       echo -e " \e[1;31m #Invalid option! \e[0m "
fi
fi
done
